# -*- coding: utf-8 -*-
"""ACMR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tZ5r5bzYNKR8KymjG03uu-eC__ZEn-O
"""

from numpy import double
import csv


def spectral_O():
      if(double(row[3]) >= -10.0 and double(row[3]) <= -7.7 and int(row[0]) >= 37800 and int(row[0]) <= 54000): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()

def spectral_B():
      if(double(row[3]) >= 0.29 and double(row[3]) <= -6.0 and int(row[0]) >= 11400 and int(row[0]) <= 29200): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= -9 and double(row[3]) <= -4.2 and int(row[0]) >= 9700 and int(row[0]) <= 21000): #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()


def spectral_A():
      if(double(row[3]) >= 1.4 and double(row[3]) <= 2.7  and int(row[0]) >= 7920 and int(row[0]) <= 9600): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= 	-6.2 and double(row[3]) <= 	-6.1  and int(row[0]) >= 8300 and int(row[0]) <= 9400): #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()

def spectral_F():
      if(double(row[3]) >= 	3.2 and double(row[3]) <= 4.2 and int(row[0]) >= 6300 and int(row[0]) <= 7350): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= -6 and double(row[3]) <= -5.9 and int(row[0]) >= 6150 and int(row[0]) <= 7500): #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()


def spectral_G():
      if(double(row[3]) >= 4.5  and double(row[3]) <= 5.2 and int(row[0]) >= 5440 and int(row[0]) <= 6050): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= -5.9  and double(row[3]) <= -5.7 and int(row[0]) >= 5050 and int(row[0]) <= 5800):  #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= 0.6  and double(row[3]) <= 0.7 and int(row[0]) >= 4870 and int(row[0]) <= 5010): #check if giant
          print("Giant star found! with the attributes:");
          printAttributes()

def spectral_K():
      if(double(row[3]) >= 5.4 and double(row[3]) <= 7.3  and int(row[0]) >= 4000 and int(row[0]) < 5240): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= -5.7  and double(row[3]) <=-5.5  and int(row[0]) >= 3750 and int(row[0]) < 4900): #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()
      elif(double(row[3]) >= -0.2 and double(row[3]) <= 0.5  and int(row[0]) >= 3780 and int(row[0]) < 4720): #check if giant
          print("Giant star found! with the attributes:");
          printAttributes()

def spectral_M():
        if(double(row[3]) >= 7.7  and double(row[3]) <= 	9.9  and int(row[0]) >= 2700 and int(row[0]) <= 3750): #check if in main sequence
          print("Main Sequence star found! with the attributes:");
          printAttributes()
        elif(double(row[3]) >= -5.3 and double(row[3]) <= -5.2 and int(row[0]) >= 2950 and int(row[0]) <= 3660): #check if in super giant
          print("Super Giant star found! with the attributes:");
          printAttributes()
        elif(double(row[3]) >= -0.9 and double(row[3]) <= -0.4  and int(row[0]) >= 2800 and int(row[0]) <= 3660): #check if giant
          print("Giant star found! with the attributes:");
          printAttributes()

def printAttributes():
        print("Spectral Class: " + row[6])
        print("Temp: " + row[0] )
        print("Magnitude: " + row[3])
        print()

with open("/stars.csv", 'r') as file:
  csvreader = csv.reader(file)
  for row in csvreader:
    if row[6] == "O":
      spectral_O()
    elif row[6] == "B":
      spectral_B()
    elif row[6] == "A":
      spectral_A()
    elif row[6] == "F":
      spectral_F()
    elif row[6] == "G":
      spectral_G()
    elif row[6] == "K":
      spectral_K()
    elif row[6] == "M":
      spectral_M()